<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Participants - {{ $event->title }}</title>
    <style>
        body {
            font-family: "Helvetica", Arial, sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            padding: 20px 0;
            border-bottom: 1px solid #ccc;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            font-weight: 600;
            color: #222;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 11px;
            color: #555;
        }

        .event-info {
            margin: 20px 0;
            padding: 15px;
            background-color: #fafafa;
            border-radius: 6px;
            border: 1px solid #eee;
        }
        .event-info h2 {
            margin: 0 0 10px 0;
            font-size: 16px;
            font-weight: 600;
            color: #222;
        }
        .event-details {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
        }
        .event-detail {
            font-size: 11px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 11px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            color: #222;
            font-weight: 600;
        }
        tr:nth-child(even) {
            background-color: #fafafa;
        }

       

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Event Participants List</h1>
        <p>Generated on: {{ now()->format('d M Y, H:i') }}</p>
    </div>

    <div class="event-info">
        <h2>{{ $event->title }}</h2>
        <div class="event-details">
            <div class="event-detail"><strong>Date & Time:</strong> {{ $event->datetime ? $event->datetime->format('d M Y, H:i') : 'Not set' }}</div>
            <div class="event-detail"><strong>Location:</strong> {{ $event->location }}</div>
            <div class="event-detail"><strong>Speaker:</strong> {{ $event->intervenant ?? 'Not specified' }}</div>
            <div class="event-detail"><strong>Club:</strong> {{ $event->club->name ?? 'Not specified' }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Class</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($participants as $participant)
                <tr>
                    <td>{{ $participant->user->nom ?? '-' }} {{ $participant->user->prenom ?? '' }}</td>
                    <td>{{ $participant->user->email ?? '-' }}</td>
                    <td>{{ $participant->user->numero ?? '-' }}</td>
                    <td>{{ $participant->classe ?? '-' }}</td>
                    <td>
                        @if($participant->participation_status === 'registered')
                            <span class="status-registered">Registered</span>
                        @elseif($participant->participation_status === 'attended')
                            <span class="status-attended">Attended</span>
                        @elseif($participant->participation_status === 'absent')
                            <span class="status-absent">Absent</span>
                        @else
                            <span class="status-registered">Unknown</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align:center; padding:20px;">No participants found for this event.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This document was generated automatically by the ISETLink system.</p>
        <p> {{ $event->club->name  }} | Generated by: {{ auth()->user()->nom ?? 'System' }} {{ auth()->user()->prenom ?? '' }}</p>
    </div>

</body>
</html>
